name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    name: Build & Tests
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build-and-publish-image:
    runs-on: ubuntu-latest
    needs: build-and-tests
    name: Publish Docker Hub
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_CLI_ASK_PASS: "0"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wesleycosta/power-up-challenge:$(date +%s)
      
    - name: Docker Push
      run: docker push wesleycosta/power-up-challenge
